version: '3.8'

name: prisma

services:
  redis: 
    image: redis
    ports:
      - 6379:6379
  
  mongo:
    build: 
      context: ./mongo
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
    ports:
      - 27017:27017
    